#!/bin/bash

#Definimos las variables a utilizar
desplegar=0	#Agregar comentario de para que la declaramos
contra=""	#Agregamos idem anterior


#Creamos un while para recorrer los parametros
while [ $# -gt 1 ];do	#COMENTAR
	case "$1" in	
		-i) 	#COMENTAR
			desplegar=1
			shift
			;;
		-c)	#COMENTAR
			if [ -z "$2" ]; then
				echo "Error, Falta agregar la contraseña luego del parametro" >&2
				exit 2
			fi
			contra="-p $2"	#Guardo el -p y la contraseña para tirar la variable entera al useradd
			shift 2
			;;
		-*)	#COMENTAR
			echo "Error, el parametro $1 no es valido" >&2
			exit 3
			;;
	esac
done

archivo="$1"	#COMENTAR

#COMENTAR
if [ -z "$archivo" ]; then
        echo "Error, no ingreso ningun archivo" >&2
        exit 4

fi

#Probamos que funciona la lectura de los inputs con banderas
#echo "Opcion -i = $desplegar"
#echo "Contraseña = $contra"
#echo "Archivo = $archivo"

while IFS= read i; do	#En cada iteracion del while lee linea por liena y lo guarda en la variable i evitando con IFS que corte por los espacios

	#Evaluar por aca cada linea del archivo por aca con un grep evaluando los campos
	usuario=$(echo "$i" | cut -d":" -f1)
	comentario=" -c $(echo "$i" | cut -d":" -f2) "
	home=$(echo "$i" | cut -d":" -f3)
	crear=$(echo "$i" | cut -d":" -f4) 
	#si dice "SI" directamente me coloque el -m que es crear el directorio HOME en useradd
	if ( "$crear" = "SI" );do
		crear=" -m"
	elif ( "$crear" = "NO" )
		crear=" -M" #Con control previo si este campo recibe NO
	fi
	shell=$(echo "$i" | cut -d":" -f5)
	
	if [ -z "$usuario" ]; then #La comprobacion del usuario tiene que estar antes y avisar al usuario que esta mal esto lo podemos hacer con un grep al archivo linea a linea o en este mismo antes de guardar las variables
		echo "Error, el usuario esta vacio"
		exit 5
	else
	
	#La idea es que si llega hasta aca es que los controles ya estan hechos, sino que devuela errores
	#si el campo esta vacio habrìa que llenarlo con algo para 
	useradd$crear $usuario $comentario $home $shell 2> /dev/null  
	#Probar que pasa si queda algo vacio, lo crea por defecto? o error?

	#Si esta el -i levantado utilizo la variable desplegar=1 para buscar el nombre en /etc/passwd, evaluar si ya fue creado o no y que hacer aca
	
done < "$archivo"



